version: "3.8"

services:
  # 1. Portainer (GUI Management untuk Docker)
  # portainer:
  #   image: portainer/portainer-ce:latest
  #   container_name: local-portainer
  #   restart: always
  #   ports:
  #     - "9443:9443"
  #     - "9000:9000"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data

  # 2. PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: local-postgres
    deploy:
      resources:
        limits:
          memory: 512M
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 3. All-in-One Custom Go Kafka Engine (pocketkafka)
  #    Single Binary Container:
  #    - Port 9092 & 29092: Kafka Wire Protocol (Menggantikan Redpanda/Kafka)
  #    - Port 8080: Embedded Web UI Dashboard (Menggantikan Kadeck Web)
  #    - Port 8081: Embedded Schema Registry (Menggantikan cp-schema-registry)
  #    - Port 8082: HTTP REST Proxy
  #    Konsumsi RAM: < 60MB (Ultra Lightweight)
  kafka-engine:
    build:
      context: .
      dockerfile: Dockerfile
    image: pocketkafka:latest
    container_name: local-kafka
    deploy:
      resources:
        limits:
          memory: 128M
    restart: always
    ports:
      - "9092:9092"   # Kafka API (host / luar container)
      - "29092:29092" # Kafka API (internal docker network)
      - "6060:6060"   # pprof (debug profiling)
      - "8080:8080"   # Embedded Web UI Dashboard (Buka di browser)
      - "8081:8081"   # Embedded Schema Registry
      - "8082:8082"   # HTTP REST Proxy Gateway
      - "1883:1883"   # MQTT Bridge (IoT)
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://local-kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_ENABLE_WEB_UI=true
      - KAFKA_ENABLE_SCHEMA_REGISTRY=true
      - KAFKA_ENABLE_REST_PROXY=true
      - KAFKA_DATA_DIR=/var/lib/pocketkafka/data
      - KAFKA_LOG_LEVEL=info
      - KAFKA_PPROF_LISTEN=0.0.0.0:6060
    volumes:
      - kafka_data:/var/lib/pocketkafka/data
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  portainer_data:
  postgres_data:
  kafka_data:
